- name: Apt transport package
  become: true
  apt:
    name: apt-transport-https
    state: latest
    update_cache: true

- name: Download Logstash Deb Package
  apt_repository:
   repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
   state: present


- name: Install Logstash Deb Package
  become: yes
  apt:
    name: logstash
    update_cache: true

- name: Create Logstash Pipeline File
  become: yes
  file:
    path: /etc/logstash/conf.d/main.conf
    state: touch

- name: Add Logstash Pipeline Configuration
  become: yes
  blockinfile:
    path: /etc/logstash/conf.d/main.conf
    marker: ""
    block: |
      input {
        beats {
          port => 5044
        }
      }
      output {
        elasticsearch { hosts => ["0.0.0.0:9200"]
        }
      }
- name: Start Logstash Service
  become: yes
  service:
    name: logstash
    state: started