- hosts: all
  become: true
  pre_tasks:
    - name: update server
      apt: 
        update_cache: true
        upgrade: dist

- hosts: webservers
  become: true
  roles:
    - nginx
    - mysql
    - rabbitmq